---
output: 
  html_document:
    css: custom_styles.css
---

#### Conditional functions
<details open><summary class = 'drop'>Conditionals 101</summary>
Conditional functions `ifelse()`, `if(){ }else{ }`, and `case_when()` allow you to return results that depends on specified conditions. 

The main differences between the most common conditional functions:
<ul>
<li>`ifelse()`: Primarily for use with data frames. Takes 3 arguments: 1) the condition to test; 2) the value to return if condition is true; 3) the value to return of the condition is false. Function can only handle 2 possible outcomes, although nested `ifelse()` statements are possible (see example below). This function is vectorized, which means it's optimized for working on columns in data frames. Of the 3 conditionals, it tends to perform the fastest on large data sets.</li>
<li>`case_when()`: Primarily for use with data frames. Can take any number of condition statements and their value to return. Requires `dplyr` package to be loaded. Syntax is a bit tricky to figure out at first, but once you have it, it's about as easy as using `ifelse()`. This function is akin to SQL CASE WHEN. On large data sets, it consistently performs slower than `ifelse()`. </li>
<li>`if(){ }else{ }`: Can be used with data frames, but is more commonly used for operations outside of data frames. An example would be only running a chunk of code if a certain condition is met (e.g., if the data frame has > 0 rows, run next line of code.)<li>
</ul>

</details>
<br>

<details open><summary class = 'drop'>`ifelse()`</summary>
The `ifelse()` function takes 3 arguments organized like: `ifelse(condition == TRUE, return this, return this instead)`. The first is the condition you're testing. The second argument is what to return if the condition is met. The third is what to return if the condition is not met. You can also nest `ifelse()` to include more than 2 conditions, but it can quickly get out of hand and hard to follow (see below).

Let's start by adding a column to the NETN tree data that uses the `TreeStatusCode` to create a new column called `status` that is either live or dead conditional on the abbreviated code in `TreeStatusCode` in `trees_final`.

<p class = 'code'>Create status column conditioning on TreeStatusCode</p>
```{r statc}
# Check the levels of TreeStatusCode
table(trees_final$TreeStatusCode)
alive <- c("AB", "AL", "AS", "RS")
dead <- c("DB", "DM", "DS")

trees_final <- trees_final |> 
  mutate(status = ifelse(TreeStatusCode %in% alive, "live", "dead"))

# nested ifelse to make alive, dead, and recruit 
trees_final <- trees_final |> 
  mutate(status2 = ifelse(TreeStatusCode %in% dead, "dead",
                          ifelse(TreeStatusCode == "RS", "recruit", 
                                 "dead")))

```

Remember that we used `%in%` instead of `==` because alive has multiple status codes. We used `==` in `TreeStatusCode == "RS"` because there's only one status code considered a recruit. We could have also used `%in%` with the same results, but that would not be true for matching the alive status codes.

</details>
<br>

R also has if/else statements that look like: `if(condition 1){do this} else {do this instead}`. The separate if/else statements are better for operations outside of data frames, 


#### Summarizing with `dplyr`
<details open><summary class = 'drop'>Using `group_by()` and `summarize()`</summary>
Yesterday, we used functions like `mean()`, `min()`, and `max()` to summarize on the entire dataset. Now we're going to use those same functions to summarize data by grouping variables, such as park, year, plot, etc. The process is similar to using Totals in Access or subtotals in Excel, although it is much more flexible and efficient in R.

The `summarize()` function in dplyr is similar to `mutate()` in that it creates a new column in your data frame. The important difference is that `mutate()` always returns the same number of rows as the original data frame. The `summarize()` function returns the same number of rows as there are grouping levels in the original data frame. I will demonstrate this concept to help understand that difference.




</details>
<br>



